name: aplicacion_certamen1
description: "App con tematica de asesinos, Certamen 1"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7447
  go_router: ^13.2.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/asesinos/
