name: aplicacion_certamen1
description: "App con tematica de asesinos, Certamen 1"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7447
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.2.4
  group_list_view: ^1.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/asesinos/
    - assets/encargados/
    - assets/productos/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-VariableFont.ttf
        - asset: assets/fonts/NotoSans-Italic-VariableFont.ttf
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Bold.ttf
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Light.ttf
